//TODO try these out on someone. Do the 90 degree angles even make sense - 90 degrees to what??

export const BslAlt: { [key: string]: string } = {
  A: "Non dominant is hand open, palm up. Dominant hand is pointing with the index finger to the thumb on the other hand.",
  B: "Both hands make an O shape with all of the fingers and thumb. Hands are put together at the fingertips, like miming binoculars.",
  C: "The thumb and the index finger on the dominant hand make a semicircle shape, with the other fingers folded into a fist.",
  D: "Non dominant points with the index finger. The dominant hand's index finger and thumb form a semi circle which is placed against the stuck up index finger; the other fingers are folded.",
  E: "Non dominant hand is open, palms up. Dominant hand is pointing with the index finger to the index finger on the other hand.",
  F: "Both hands have the fingers folded apart from the indexes and middles which are straight. The dominant hand's fingers rest on top of the other hand's fingers.",
  G: "Both hands are in fists. The dominant hands rests atop the other.",
  H: "Both hands are open flat. The non dominant hand is palms up while the dominant hand is palms down. The dominant hand is placed atop the other at a 90 degree angle and slides from the base to the fingertips.",
  I: "Non dominant hand is open, palms up. Dominant hand is pointing with the index finger to the middle finger on the other hand.",
  J: "Non dominant hand is open, palm up. Dominant hand is pointing with index finger. Dominant hand draws a curve on the other palm, starting from the tip of the middle finger, going down to the base of the palm and then up to the thumb.",
  K: "The non dominant hand is pointing with the index finger. The dominant hand is in a fist apart from the index finger which is curved. The dominant index finger leans against the other.",
  L: "The non dominant hand is open, palms up. The dominant hand points with the index finger, which is rested face down on the other palm.",
  M: "The non dominant hand is open, palms up. The dominant hand's pinky and thumb are folded in. The other three fingers are pointed straight, rested face down on the non dominant palm.",
  N: "The non dominant hand is open, palms up. The dominant hand's pinky, ring finger and thumb are folded in. The other two fingers are pointed straight, rested face down on the non dominant palm.",
  O: "Non dominant hand is open, palms up. Dominant hand is pointing with the index finger to the ring finger on the other hand.",
  P: "Dominant hand has the fingers folded in, apart from the thumb and the index finger which form a circle by touching the finger tips together. The tips also touch the tip of the index finger on the non dominant hand, which is in a pointing position.",
  Q: "The non dominant hands makes an O shape using all of the fingers. The dominant hand is pointing the index finger which rests on the other hand's thumb at a 90-ish degree angle.",
  R: "The non dominant hand is open, palms up. The dominant hand is pointing with the index finger, except the index finger is curled. It rests on the palm of the non dominant hand.",
  S: "The non dominant hand is open, palms up. The non dominant hand is in a fist facing downwards except for the pinky finger. The pinky finger is curled and wrapped loosely around the pink finger of the other hand.",
  T: "The non dominant hand is open, palms up. The dominant hand is pointing with the index finger, which is touching the side of the other hand at a 90 degree angle.",
  U: "Non dominant hand is open, palms up. Dominant hand is pointing with the index finger to the pinky finger on the other hand.",
  V: "Non dominant hand is open, palms up. The dominant hand has the index and middle fingers outstretched, not touching each other. They're placed upon the non dominant hand facing downwards.",
  W: "Both hands are open, fingers outstretched. The hands are sort of clasped together, but with the fingers still straight.",
  X: "Both fingers are in pointing positions with the index finger. The dominant hand's index tip rests atop the other at a 90 degree angle.",
  Y: "The non dominant hand is open with the fingers together and thumb apart. The dominant hand is pointing with the index finger, which rests on the other hand, the tip pointing to the place where the base of the thumb and index finger meet.",
  Z: "Both hands are open with all the fingers and thumb together. The non dominant hand faces up, perpendicular to the body. The dominant hand is perpendicular to the other hand, its fingertips touching the base of the other hand's fingers.",
};
